version: "3.9"
services:
  postgres:
   image: postgres:12-alpine
   environment:
    - LANG=en_US.utf8
    - POSTGRES_USER= root
    - POSTGRES_PASSWORD= postgres123
    - POSTGRES_DB= simple_bank
   ports:
      - "5433:5432"
   
  
  api:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   environment:
     - DB_SOURCE=postgresql://root:postgres123@postgres:5432/simple_bank?sslmode=disable
   depends_on:
     - postgres
   entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
   command: ["/app/main"]