apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::250116462332:user/github-cli
      username: gitub-ci
      groups:
        - system:masters
