apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUser: |
    - userarn: arn:aws:iam::250116462332:user/github-cli
      username: github-cli
      groups:
        - system:masters

